import base64
import io
import json
import os
import re
import sys
import time
from typing import Any, Dict

# Add Open-AutoGLM to sys.path
sys.path.append(os.path.abspath("../Open-AutoGLM"))

try:
    from phone_agent.actions.handler import parse_action
    from phone_agent.agent import AgentConfig, PhoneAgent
    from phone_agent.model import ModelClient, ModelConfig
    from phone_agent.model.client import MessageBuilder
except ImportError:
    # Fallback or error handling if path is incorrect
    print("Error: Open-AutoGLM not found in ../Open-AutoGLM")
    raise

from PIL import Image

from aitk.translators.base import BaseTranslator
from aitk.utils.image_utils import smart_resize


class AutoGLMTranslator(BaseTranslator):
    def __init__(
        self,
        max_pixels: int = 1024000,
        base_url: str = "",
        api_key: str = "",
        model: str = "",
    ) -> None:
        self.max_pixels = max_pixels
        self.model = model

        # Configure model endpoint
        self.model_config = ModelConfig(
            base_url=base_url,
            api_key=api_key,
            model_name=model,
            temperature=0.0,  # AutoGLM defaults to 0.0 for actions
        )

        # Configure Agent behavior
        self.agent_config = AgentConfig(
            max_steps=50,
            verbose=True,
            lang="en",  # Default to English
        )

        # Create Model Client directly
        self.model_client = ModelClient(self.model_config)

    def to_device(self, action: str, width: int, height: int) -> dict:
        """transform the string generated by agent to the action that can be executed on the device"""

        # Extract action part if wrapped in <think>...</think><answer>...</answer>
        # Simple regex to remove <think> blocks if present
        cleaned_action = re.sub(
            r"<think>.*?</think>", "", action, flags=re.DOTALL
        ).strip()
        cleaned_action = re.sub(
            r"<answer>(.*?)</answer>", r"\1", cleaned_action, flags=re.DOTALL
        ).strip()

        if not cleaned_action:
            return {"action": "end", "answer": "No action generated"}

        try:
            # Use AutoGLM's parser
            parsed_action = parse_action(cleaned_action)
        except ValueError as e:
            return {"action": "end", "answer": f"Parse Error: {e}"}

        action_name = parsed_action.get("action")

        if parsed_action.get("_metadata") == "finish":
            return {"action": "end", "answer": parsed_action.get("message", "")}

        if action_name == "Tap":
            # AutoGLM uses relative [x, y] in 0-1000
            element = parsed_action.get("element")
            if not element:
                return {"action": "end", "answer": "Tap missing coordinates"}
            x = int(element[0] / 1000 * width)
            y = int(element[1] / 1000 * height)
            return {"action": "tap", "x": x, "y": y}

        elif action_name == "Long Press":
            element = parsed_action.get("element")
            if not element:
                return {"action": "end", "answer": "Long Press missing coordinates"}
            x = int(element[0] / 1000 * width)
            y = int(element[1] / 1000 * height)
            return {"action": "long_press", "x": x, "y": y}

        elif action_name == "Double Tap":
            element = parsed_action.get("element")
            if not element:
                return {"action": "end", "answer": "Double Tap missing coordinates"}
            x = int(element[0] / 1000 * width)
            y = int(element[1] / 1000 * height)
            return {"action": "double_tap", "x": x, "y": y}

        elif action_name == "Type" or action_name == "Type_Name":
            text = parsed_action.get("text", "")
            return {"action": "type", "text": text}

        elif action_name == "Swipe":
            start = parsed_action.get("start")
            end = parsed_action.get("end")
            if not start or not end:
                return {"action": "end", "answer": "Swipe missing coordinates"}
            x1 = int(start[0] / 1000 * width)
            y1 = int(start[1] / 1000 * height)
            x2 = int(end[0] / 1000 * width)
            y2 = int(end[1] / 1000 * height)
            return {
                "action": "swipe",
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "duration": 1000,
            }

        elif action_name == "Back":
            return {"action": "back"}

        elif action_name == "Home":
            return {"action": "home"}

        elif action_name == "Enter":
            return {"action": "enter"}

        elif action_name == "Wait":
            # AutoGLM Wait has 'duration' string like "1 seconds"
            duration_str = parsed_action.get("duration", "1")
            try:
                duration = float(str(duration_str).replace("seconds", "").strip())
            except ValueError:
                duration = 1.0
            return {"action": "wait", "time": duration}

        elif action_name == "Launch":
            return {"action": "open", "app": parsed_action.get("app", "")}

        # Fallback for unsupported actions
        return {"action": "end", "answer": f"Unsupported action: {action_name}"}

    def resize(self, screenshot: str) -> str:
        image = base64.b64decode(screenshot)
        image_stream = io.BytesIO(image)
        image = Image.open(image_stream)
        width, height = image.size
        # Using smart_resize utilities from AITK
        new_height, new_width, h_beta, w_beta = smart_resize(
            height, width, max_pixels=self.max_pixels
        )
        self.h_beta = h_beta
        self.w_beta = w_beta
        image_resized = image.resize((new_width, new_height))
        buffer = io.BytesIO()
        image_resized.save(buffer, format="PNG")
        image_bytes = buffer.getvalue()
        base64_str = base64.b64encode(image_bytes).decode("utf-8")
        return base64_str

    def to_agent(self, task: str, state: dict, history: dict) -> str:
        """Given the task, current state and the agent history, interact with the agent and get the output"""

        screenshot = state["screenshot"]
        screenshot = self.resize(screenshot)

        current_package = state.get("package", "Unknown")
        # Build current app info string
        screen_info_str = json.dumps(
            {"current_app": current_package}, ensure_ascii=False
        )

        # Construct Messages
        messages = []

        # 1. System Message
        messages.append(
            MessageBuilder.create_system_message(self.agent_config.system_prompt)
        )

        # 2. History
        num_steps = len(history.get("actions", []))

        for i in range(num_steps):
            is_first_step = i == 0

            # Reconstruct User Message (Text Only for history)
            if is_first_step:
                # Approximation: we don't have the original screen_info for step 0
                user_text = f"{task}\n\n[Screen Info Omitted for History]"
            else:
                user_text = f"** Screen Info **\n\n[Screen Info Omitted for History]"

            messages.append(
                MessageBuilder.create_user_message(text=user_text, image_base64=None)
            )

            # Add Assistant Message (Model Output)
            # We trust that history['agent_messages'] contains the response we generated previously
            agent_response = history["agent_messages"][i]
            # Strip <think> tags if you want to optimize tokens, but usually keeping them is fine for context
            messages.append(MessageBuilder.create_assistant_message(agent_response))

        # 3. Current Step
        is_current_first = num_steps == 0

        if is_current_first:
            text_content = f"{task}\n\n{screen_info_str}"
        else:
            text_content = f"** Screen Info **\n\n{screen_info_str}"

        # Add Current User Message WITH Image
        messages.append(
            MessageBuilder.create_user_message(
                text=text_content, image_base64=screenshot
            )
        )

        # 4. Request
        try:
            # ModelClient.request returns a ModelResponse object
            response = self.model_client.request(messages)

            # Format: <think>...</think><answer>...</answer>
            full_response = (
                f"<think>{response.thinking}</think><answer>{response.action}</answer>"
            )
            return full_response

        except Exception as e:
            # Return error as answer so it can be handled
            return f'<answer>finish(message="Error: {str(e)}")</answer>'
