class BaseTranslator:
    def __init__(self) -> None:
        pass

    def to_device(self, action: str, width: int, height: int) -> dict:
        """transform the string generated by agent to the action that can be executed on the device

        Args:
            action (Any): any action generated by agent

        Returns:
            dict: a dictionary containing the action that can be executed on the device. The format is like:
                    {"action": "open", "app": "youtube"}
                    {"action": "tap", "x": 100, "y": 100}
                    {"action": "long_press", "x": 100, "y": 100, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "swipe", "x1": 100, "y1": 100, "x2": 200, "y2": 200, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "type", "text": "hello"}
                    {"action": "enter"}
                    {"action": "back"}
                    {"action": "home"}
                    {"action": "wait", "time": 1 (optional, default to 3 second)}
                    {"action": "end", "answer": "answer to the user query (default to empty string)"}
        """
        return {}

    def to_agent(self, task: str, state: dict, history: dict) -> str:
        """Given the task, current state and the agent history, interact with the agent and get the output

        Args:
            task (str): the task to be executed
            state (dict): the current state of the device
                - xml: the XML of the current state of the device in string format
                - screenshot: the screenshot of the current state of the device in base64 format
                - package: the package of the current app
                - activity: the activity of the current app
            history (dict): the history of the device in the current task
                - xmls: a list of XMLs of the device in the previous steps
                - screenshots: a list of screenshots of the device in the previous steps
                - actions: a list of actions of the device in the previous steps
                - agent_messages: a list of messages from the agent in the previous steps
                - packages: a list of packages of the apps in the previous steps
                - activities: a list of activities of the apps in the previous steps
        Returns:
            str: the output generated by the agent
        """
        return "CLICK[100,100]"
