import base64
import json
import math
import re

import cv2
import numpy as np
import pyshine as ps
import requests

from aitk.translators.base import BaseTranslator
from aitk.utils.xml_processor import XMLCleaner


class Qwen25VLTranslator(BaseTranslator):
    def __init__(self, sk: str = "empty") -> None:
        self.url = "http://nluoss-ai.vivo.com.cn/qwen25vl"

    def get_resize_factor(self, width: int, height: int, maxpixel: int) -> float:
        if width * height > maxpixel:
            return math.sqrt(maxpixel / (width * height))
        else:
            return 1.0

    def to_device(self, action: str, width: int, height: int) -> dict:
        """transform the string generated by agent to the action that can be executed on the device

        Args:
            action (Any): any action generated by agent

        Returns:
            dict: a dictionary containing the action that can be executed on the device. The format is like:
                    {"action": "open", "app": "youtube"}
                    {"action": "tap", "x": 100, "y": 100}
                    {"action": "long_press", "x": 100, "y": 100, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "swipe", "x1": 100, "y1": 100, "x2": 200, "y2": 200, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "type", "text": "hello"}
                    {"action": "enter"}
                    {"action": "back"}
                    {"action": "home"}
                    {"action": "wait", "time": 1 (optional, default to 3 second)}
                    {"action": "end", "answer": "answer to the user query (default to empty string)"}
        """
        action_str = re.search(r"<tool_call>\s*(.*)\s*</tool_call>", action)
        if not action_str:
            return {"action": "end", "answer": ""}

        resize_factor = self.get_resize_factor(width, height, 602112)
        action_str = action_str.group(1).strip()
        try:
            action_dict = json.loads(action_str)
            action_dict = action_dict["arguments"]
        except Exception as e:
            return {"action": "end", "answer": ""}

        if action_dict.get("action") == "click":
            if action_dict.get("som") is not None:
                index = int(action_dict.get("som")) - 1
                element = self.current_elements[index]
                x1, y1, x2, y2 = element["bounds"]
                x = (x1 + x2) // 2
                y = (y1 + y2) // 2
            else:
                x, y = action_dict.get("coordinate", [None, None])
                if x is None or y is None:
                    return {"action": "end", "answer": ""}
                x, y = int(x / resize_factor), int(y / resize_factor)
            return {"action": "tap", "x": x, "y": y}
        elif action_dict.get("action") == "long_press":
            if action_dict.get("som") is not None:
                index = int(action_dict.get("som")) - 1
                element = self.current_elements[index]
                x1, y1, x2, y2 = element["bounds"]
                x = (x1 + x2) // 2
                y = (y1 + y2) // 2
            else:
                x, y = action_dict.get("coordinate", [None, None])
                if x is None or y is None:
                    return {"action": "end", "answer": ""}
                x, y = int(x / resize_factor), int(y / resize_factor)
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 1000
            return {"action": "long_press", "x": x, "y": y, "duration": time}
        elif action_dict.get("action") == "swipe":
            if (
                action_dict.get("coordinate") is not None
                and action_dict.get("coordinate2") is not None
            ):
                x1, y1 = action_dict.get("coordinate", [None, None])
                x2, y2 = action_dict.get("coordinate2", [None, None])
                x1, y1 = int(x1 / resize_factor), int(y1 / resize_factor)
                x2, y2 = int(x2 / resize_factor), int(y2 / resize_factor)
            elif action_dict.get("direction") is not None:
                direction = action_dict.get("direction")
                if direction == "up":
                    x1, y1 = width // 2, height * 3 // 4
                    x2, y2 = width // 2, height // 4
                elif direction == "down":
                    x1, y1 = width // 2, height // 4
                    x2, y2 = width // 2, height * 3 // 4
                elif direction == "left":
                    x1, y1 = width * 4 // 5, height // 2
                    x2, y2 = width // 5, height // 2
                elif direction == "right":
                    x1, y1 = width // 5, height // 2
                    x2, y2 = width * 4 // 5, height // 2
            else:
                return {"action": "end", "answer": ""}
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 1000
            return {
                "action": "swipe",
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "duration": time,
            }
        elif action_dict.get("action") == "type":
            text = action_dict.get("text", "")
            return {"action": "type", "text": text}
        elif action_dict.get("action") == "system_button":
            button = action_dict.get("button", "")
            if button == "Back":
                return {"action": "back"}
            elif button == "Home":
                return {"action": "home"}
            elif button == "Enter":
                return {"action": "enter"}
        elif action_dict.get("action") == "open":
            app_name = action_dict.get("text", "")
            return {"action": "open", "app": app_name.lower()}
        elif action_dict.get("action") == "wait":
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 3
            return {"action": "wait", "time": time}
        elif action_dict.get("action") == "terminate":
            status = action_dict.get("status", "")
            return {"action": "end", "answer": status}

    def to_agent(self, task: str, state: dict, history: dict) -> str:
        """Given the task, current state and the agent history, interact with the agent and get the output

        Args:
            task (str): the task to be executed
            state (dict): the current state of the device
                - xml: the XML of the current state of the device in string format
                - screenshot: the screenshot of the current state of the device in base64 format
                - package: the package of the current app
                - activity: the activity of the current app
            history (dict): the history of the device in the current task
                - xmls: a list of XMLs of the device in the previous steps
                - screenshots: a list of screenshots of the device in the previous steps
                - actions: a list of actions of the device in the previous steps
                - agent_messages: a list of messages from the agent in the previous steps
                - packages: a list of packages of the apps in the previous steps
                - activities: a list of activities of the apps in the previous steps
        Returns:
            str: the output generated by the agent
        """
        screenshot = state["screenshot"]

        # ------------------------------SOM----------------------------#
        xml = state["xml"]
        xml_cleaner = XMLCleaner(xml)
        elements = xml_cleaner.get_final_elements()
        self.current_elements = elements

        # Decode base64 to numpy array
        img_bytes = base64.b64decode(screenshot)
        img_array = np.frombuffer(img_bytes, dtype=np.uint8)
        imgcv = cv2.imdecode(img_array, cv2.IMREAD_COLOR)
        for i, element in enumerate(elements):
            try:
                x1, y1, x2, y2 = element["bounds"]
                label = i + 1
                color = (250, 0, 0)
                imgcv = ps.putBText(
                    imgcv,
                    label,
                    text_offset_x=(x1 + x2) // 2 + 10,
                    text_offset_y=(y1 + y2) // 2 + 10,
                    vspace=10,
                    hspace=10,
                    font_scale=1,
                    thickness=2,
                    background_RGB=color,
                    text_RGB=(255, 250, 250),
                    alpha=0.5,
                )
            except Exception as e:
                pass
        _, buffer = cv2.imencode(".png", imgcv)
        screenshot = base64.b64encode(buffer).decode("utf-8")
        # ------------------------------SOM----------------------------#

        history_actions = []
        for m in history["agent_messages"]:
            pattern = r"<tool_call>\s*(.*)\s*</tool_call>"
            match = re.search(pattern, m)
            if match:
                m_str = match.group(1).strip()
            else:
                m_str = json.dumps({"action": "end", "answer": ""})
            try:
                dic = json.loads(m_str)
                action = dic["arguments"]
                history_actions.append(action["action_desc"])
            except Exception as e:
                history_actions.append(m_str)

        action_history_str = []
        for i, action in enumerate(history_actions):
            action_history_str.append(f"Step{i+1}: {action}")
        action_history_str = "\n".join(action_history_str)

        user_prompt = f"The user query:  {task}\nTask progress (You have done the following operation on the current device): {action_history_str};"

        request_data = {"query": user_prompt, "images": [screenshot]}

        response = requests.post(
            self.url,
            json=request_data,
            headers={"Content-Type": "application/json"},
        )
        response_data = json.loads(response.text)
        response_str = response_data["result"]

        return response_str


def register() -> Qwen25VLTranslator:
    return Qwen25VLTranslator()
