import base64
import io
import json
import math
import re

import numpy as np
from openai import OpenAI
from PIL import Image

from aitk.translators.base import BaseTranslator
from aitk.utils.image_utils import smart_resize


class Qwen3VLTranslator(BaseTranslator):
    def __init__(
        self,
        max_pixels: int = 1024000,
        base_url: str = "v-dev-research4gpu-11179700-vllm1-wl0101-vtraining.vmic.xyz/v1/",
        api_key: str = "empty",
        model: str = "qwen3vl_a3b",
    ) -> None:
        self.client = OpenAI(
            base_url=base_url,
            api_key=api_key,
        )
        self.max_pixels = max_pixels
        self.model = model

    def to_device(self, action: str, width: int, height: int) -> dict:
        """transform the string generated by agent to the action that can be executed on the device

        Args:
            action (Any): any action generated by agent

        Returns:
            dict: a dictionary containing the action that can be executed on the device. The format is like:
                    {"action": "open", "app": "youtube"}
                    {"action": "tap", "x": 100, "y": 100}
                    {"action": "long_press", "x": 100, "y": 100, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "swipe", "x1": 100, "y1": 100, "x2": 200, "y2": 200, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "type", "text": "hello"}
                    {"action": "enter"}
                    {"action": "back"}
                    {"action": "home"}
                    {"action": "wait", "time": 1 (optional, default to 3 second)}
                    {"action": "end", "answer": "answer to the user query (default to empty string)"}
        """
        action_str = re.search(r"<tool_call>(.*)</tool_call>", action, re.DOTALL)
        if not action_str:
            return {"action": "end", "answer": "No format output"}

        action_str = action_str.group(1).strip()
        try:
            action_dict = json.loads(action_str)
            action_dict = action_dict["arguments"]
        except Exception as e:
            return {"action": "end", "answer": f"{e}"}

        if action_dict.get("action") == "click":
            x, y = action_dict.get("coordinate", [None, None])
            if x is None or y is None:
                return {"action": "end", "answer": "Click not parsed"}
            x, y = int(x / 1000 * width), int(y / 1000 * height)
            return {"action": "tap", "x": x, "y": y}
        elif action_dict.get("action") == "long_press":
            x, y = action_dict.get("coordinate", [None, None])
            if x is None or y is None:
                return {"action": "end", "answer": "Long Press not parsed"}
            x, y = int(x / 1000 * width), int(y / 1000 * height)
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 1000
            return {"action": "long_press", "x": x, "y": y, "duration": time}
        elif action_dict.get("action") == "swipe":
            if (
                action_dict.get("coordinate") is not None
                and action_dict.get("coordinate2") is not None
            ):
                x1, y1 = action_dict.get("coordinate", [None, None])
                x2, y2 = action_dict.get("coordinate2", [None, None])
                x1, y1 = int(x1 / 1000 * width), int(y1 / 1000 * height)
                x2, y2 = int(x2 / 1000 * width), int(y2 / 1000 * height)
            elif action_dict.get("direction") is not None:
                direction = action_dict.get("direction")
                if direction == "up":
                    x1, y1 = width // 2, height * 3 // 4
                    x2, y2 = width // 2, height // 4
                elif direction == "down":
                    x1, y1 = width // 2, height // 4
                    x2, y2 = width // 2, height * 3 // 4
                elif direction == "left":
                    x1, y1 = width * 4 // 5, height // 2
                    x2, y2 = width // 5, height // 2
                elif direction == "right":
                    x1, y1 = width // 5, height // 2
                    x2, y2 = width * 4 // 5, height // 2
            else:
                return {"action": "end", "answer": "Swipe not parsed"}
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 1000
            return {
                "action": "swipe",
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "duration": time,
            }
        elif action_dict.get("action") == "type":
            if "text" in action_dict:
                return {"action": "type", "text": action_dict.get("text", "")}
            return {"action": "end", "answer": "Type text not parsed"}
        elif action_dict.get("action") == "system_button":
            button = action_dict.get("button", "")
            if button == "Back":
                return {"action": "back"}
            elif button == "Home":
                return {"action": "home"}
            elif button == "Enter":
                return {"action": "enter"}
            else:
                return {"action": "end", "answer": "System button not parsed"}
        elif action_dict.get("action") == "open":
            if "text" in action_dict:
                app_name = action_dict.get("text", "")
                return {"action": "open", "app": app_name.lower()}
            return {"action": "end", "answer": "Open app not parsed"}
        elif action_dict.get("action") == "wait":
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 3
            return {"action": "wait", "time": time}
        elif action_dict.get("action") == "terminate":
            status = action_dict.get("status", "")
            return {"action": "end", "answer": status}
        elif action_dict.get("action") == "answer":
            return {"action": "end", "answer": action_dict.get("answer", "")}
        elif action_dict.get("action") == "error":
            return {"action": "end", "answer": action_dict.get("answer", "")}
        else:
            return {"action": "end", "answer": "unknown action"}

    def resize(self, screenshot: str) -> str:
        image = base64.b64decode(screenshot)
        image_stream = io.BytesIO(image)
        image = Image.open(image_stream)
        width, height = image.size
        new_height, new_width, h_beta, w_beta = smart_resize(
            height, width, max_pixels=self.max_pixels
        )
        self.h_beta = h_beta
        self.w_beta = w_beta
        image_resized = image.resize((new_width, new_height))
        buffer = io.BytesIO()
        image_resized.save(buffer, format="PNG")
        image_bytes = buffer.getvalue()
        base64_str = base64.b64encode(image_bytes).decode("utf-8")
        return base64_str

    def to_agent(self, task: str, state: dict, history: dict) -> str:
        """Given the task, current state and the agent history, interact with the agent and get the output

        Args:
            task (str): the task to be executed
            state (dict): the current state of the device
                - xml: the XML of the current state of the device in string format
                - screenshot: the screenshot of the current state of the device in base64 format
                - package: the package of the current app
                - activity: the activity of the current app
            history (dict): the history of the device in the current task
                - xmls: a list of XMLs of the device in the previous steps
                - screenshots: a list of screenshots of the device in the previous steps
                - actions: a list of actions of the device in the previous steps
                - agent_messages: a list of messages from the agent in the previous steps
                - packages: a list of packages of the apps in the previous steps
                - activities: a list of activities of the apps in the previous steps
        Returns:
            str: the output generated by the agent
        """
        system_prompt = '\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>\n{"type": "function", "function": {"name": "mobile_use", "description": "Use a touchscreen to interact with a mobile device, and take screenshots.\\n* This is an interface to a mobile device with touchscreen. You can perform actions like clicking, typing, swiping, etc.\\n* Some applications may take time to start or process actions, so you may need to wait and take successive screenshots to see the results of your actions.\\n* The screen\'s resolution is 999x999.\\n* Make sure to click any buttons, links, icons, etc with the cursor tip in the center of the element. Don\'t click boxes on their edges unless asked.", "parameters": {"properties": {"action": {"description": "The action to perform. The available actions are:\\n* `click`: Click the point on the screen with coordinate (x, y).\\n* `long_press`: Press the point on the screen with coordinate (x, y) for specified seconds.\\n* `swipe`: Swipe from the starting point with coordinate (x, y) to the end point with coordinates2 (x2, y2).\\n* `type`: Input the specified text into the activated input box.\\n* `answer`: Output the answer.\\n* `system_button`: Press the system button.\\n* `wait`: Wait specified seconds for the change to happen.\\n* `terminate`: Terminate the current task and report its completion status.", "enum": ["click", "long_press", "swipe", "type", "answer", "system_button", "wait", "terminate"], "type": "string"}, "coordinate": {"description": "(x, y): The x (pixels from the left edge) and y (pixels from the top edge) coordinates to move the mouse to. Required only by `action=click`, `action=long_press`, and `action=swipe`.", "type": "array"}, "coordinate2": {"description": "(x, y): The x (pixels from the left edge) and y (pixels from the top edge) coordinates to move the mouse to. Required only by `action=swipe`.", "type": "array"}, "text": {"description": "Required only by `action=type` and `action=answer`.", "type": "string"}, "time": {"description": "The seconds to wait. Required only by `action=long_press` and `action=wait`.", "type": "number"}, "button": {"description": "Back means returning to the previous interface, Home means returning to the desktop, Menu means opening the application background menu, and Enter means pressing the enter. Required only by `action=system_button`", "enum": ["Back", "Home", "Menu", "Enter"], "type": "string"}, "status": {"description": "The status of the task. Required only by `action=terminate`.", "type": "string", "enum": ["success", "failure"]}}, "required": ["action"], "type": "object"}}}\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{"name": <function-name>, "arguments": <args-json-object>}\n</tool_call>\n\n# Response format\n\nResponse format for every step:\n1) Thought: one concise sentence explaining the next move (no multi-step reasoning).\n2) Action: a short imperative describing what to do in the UI.\n3) A single <tool_call>...</tool_call> block containing only the JSON: {"name": <function-name>, "arguments": <args-json-object>}.\n\nRules:\n- Output exactly in the order: Thought, Action, <tool_call>.\n- Be brief: one sentence for Thought, one for Action.\n- Do not output anything else outside those three parts.\n- If finishing, use action=terminate in the tool call.'

        screenshot = state["screenshot"]

        screenshot = self.resize(screenshot)

        history_actions = []
        for m in history["agent_messages"]:
            pattern = r"Action:(.*)<tool_call>"
            match = re.search(pattern, m, re.DOTALL)
            if match:
                m_str = match.group(1).strip()
            else:
                m_str = None
            if m_str is not None:
                history_actions.append(m_str)
            else:
                history_actions.append("")

        action_history_str = []
        for i, action in enumerate(history_actions):
            action_history_str.append(f"Step {i+1}: {action}")
        action_history_str = "; ".join(action_history_str)

        user_prompt = f"The user query:  {task}\nTask progress (You have done the following operation on the current device): {action_history_str}; "

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": user_prompt},
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image;base64,{screenshot}"},
                        },
                    ],
                },
            ],
        )
        response_str = response.choices[0].message.content
        return response_str


def register(kargs: dict) -> Qwen3VLTranslator:
    return Qwen3VLTranslator(**kargs)
