import base64
import io
import json
import math
import re

import numpy as np
from openai import OpenAI
from PIL import Image

from aitk.translators.base import BaseTranslator
from aitk.utils.image_utils import smart_resize


class Qwen25VLTranslator(BaseTranslator):
    def __init__(self, max_pixels: int = 784000) -> None:
        self.client = OpenAI(
            base_url="http://v-dev-dev-11185398-vllm-wl0101-vtraining.vmic.xyz/v1/",
            api_key="empty",
        )
        self.max_pixels = max_pixels

    def to_device(self, action: str, width: int, height: int) -> dict:
        """transform the string generated by agent to the action that can be executed on the device

        Args:
            action (Any): any action generated by agent

        Returns:
            dict: a dictionary containing the action that can be executed on the device. The format is like:
                    {"action": "open", "app": "youtube"}
                    {"action": "tap", "x": 100, "y": 100}
                    {"action": "long_press", "x": 100, "y": 100, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "swipe", "x1": 100, "y1": 100, "x2": 200, "y2": 200, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "type", "text": "hello"}
                    {"action": "enter"}
                    {"action": "back"}
                    {"action": "home"}
                    {"action": "wait", "time": 1 (optional, default to 3 second)}
                    {"action": "end", "answer": "answer to the user query (default to empty string)"}
        """
        action_str = re.search(r"<tool_call>\s*(.*)\s*</tool_call>", action)
        if not action_str:
            return {"action": "end", "answer": "No format output"}

        h_beta = self.h_beta
        w_beta = self.w_beta
        action_str = action_str.group(1).strip()
        try:
            action_dict = json.loads(action_str)
            action_dict = action_dict["arguments"]
        except Exception as e:
            return {"action": "end", "answer": f"{e}"}

        if action_dict.get("action") == "click":
            x, y = action_dict.get("coordinate", [None, None])
            if x is None or y is None:
                return {"action": "end", "answer": "Click not parsed"}
            x, y = int(x / w_beta), int(y / h_beta)
            return {"action": "tap", "x": x, "y": y}
        elif action_dict.get("action") == "long_press":
            x, y = action_dict.get("coordinate", [None, None])
            if x is None or y is None:
                return {"action": "end", "answer": "Long Press not parsed"}
            x, y = int(x / w_beta), int(y / h_beta)
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 1000
            return {"action": "long_press", "x": x, "y": y, "duration": time}
        elif action_dict.get("action") == "swipe":
            if (
                action_dict.get("coordinate") is not None
                and action_dict.get("coordinate2") is not None
            ):
                x1, y1 = action_dict.get("coordinate", [None, None])
                x2, y2 = action_dict.get("coordinate2", [None, None])
                x1, y1 = int(x1 / w_beta), int(y1 / h_beta)
                x2, y2 = int(x2 / w_beta), int(y2 / h_beta)
            elif action_dict.get("direction") is not None:
                direction = action_dict.get("direction")
                if direction == "up":
                    x1, y1 = width // 2, height * 3 // 4
                    x2, y2 = width // 2, height // 4
                elif direction == "down":
                    x1, y1 = width // 2, height // 4
                    x2, y2 = width // 2, height * 3 // 4
                elif direction == "left":
                    x1, y1 = width * 4 // 5, height // 2
                    x2, y2 = width // 5, height // 2
                elif direction == "right":
                    x1, y1 = width // 5, height // 2
                    x2, y2 = width * 4 // 5, height // 2
            else:
                return {"action": "end", "answer": "Swipe not parsed"}
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 1000
            return {
                "action": "swipe",
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "duration": time,
            }
        elif action_dict.get("action") == "type":
            if "text" in action_dict:
                return {"action": "type", "text": action_dict.get("text", "")}
            return {"action": "end", "answer": "Type text not parsed"}
        elif action_dict.get("action") == "system_button":
            button = action_dict.get("button", "")
            if button == "Back":
                return {"action": "back"}
            elif button == "Home":
                return {"action": "home"}
            elif button == "Enter":
                return {"action": "enter"}
            else:
                return {"action": "end", "answer": "System button not parsed"}
        elif action_dict.get("action") == "open":
            if "text" in action_dict:
                app_name = action_dict.get("text", "")
                return {"action": "open", "app": app_name.lower()}
            return {"action": "end", "answer": "Open app not parsed"}
        elif action_dict.get("action") == "wait":
            if action_dict.get("time") is not None:
                time = action_dict.get("time")
            elif action_dict.get("duration") is not None:
                time = action_dict.get("duration")
            else:
                time = 3
            return {"action": "wait", "time": time}
        elif action_dict.get("action") == "terminate":
            status = action_dict.get("status", "")
            return {"action": "end", "answer": status}
        else:
            return {"action": "end", "answer": "unknown action"}

    def resize(self, screenshot: base64) -> base64:
        image = base64.b64decode(screenshot)
        image_stream = io.BytesIO(image)
        image = Image.open(image_stream)
        width, height = image.size
        new_height, new_width, h_beta, w_beta = smart_resize(
            height, width, max_pixels=self.max_pixels
        )
        self.h_beta = h_beta
        self.w_beta = w_beta
        image_resized = image.resize((new_width, new_height))
        buffer = io.BytesIO()
        image_resized.save(buffer, format="PNG")
        image_bytes = buffer.getvalue()
        base64_str = base64.b64encode(image_bytes).decode("utf-8")
        return base64_str

    def to_agent(self, task: str, state: dict, history: dict) -> str:
        """Given the task, current state and the agent history, interact with the agent and get the output

        Args:
            task (str): the task to be executed
            state (dict): the current state of the device
                - xml: the XML of the current state of the device in string format
                - screenshot: the screenshot of the current state of the device in base64 format
                - package: the package of the current app
                - activity: the activity of the current app
            history (dict): the history of the device in the current task
                - xmls: a list of XMLs of the device in the previous steps
                - screenshots: a list of screenshots of the device in the previous steps
                - actions: a list of actions of the device in the previous steps
                - agent_messages: a list of messages from the agent in the previous steps
                - packages: a list of packages of the apps in the previous steps
                - activities: a list of activities of the apps in the previous steps
        Returns:
            str: the output generated by the agent
        """
        system_prompt = """
You are a helpful assistant.

# Tools

You may call one or more functions to assist with the user query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{"type": "function", "function": {"name_for_human": "mobile_use", "name": "mobile_use", "description": "Use a touchscreen to interact with a mobile device, and take screenshots.\n* This is an interface to a mobile device with touchscreen. You can perform actions like clicking, typing, swiping, etc.\n* Some applications may take time to start or process actions, so you may need to wait and take successive screenshots to see the results of your actions.\n* The screen's resolution is 1092x2408.\n* Make sure to click any buttons, links, icons, etc with the cursor tip in the center of the element. Don't click boxes on their edges unless asked.", "parameters": {"properties": {"action": {"description": "The action to perform. The available actions are:\n* `key`: Perform a key event on the mobile device.\n    - This supports adb's `keyevent` syntax.\n    - Examples: \"volume_up\", \"volume_down\", \"power\", \"camera\", \"clear\".\n* `click`: Click the point on the screen with coordinate (x, y).\n* `long_press`: Press the point on the screen with coordinate (x, y) for specified seconds.\n* `swipe`: Swipe from the starting point with coordinate (x, y) to the end point with coordinates2 (x2, y2).\n* `type`: Input the specified text into the activated input box.\n* `system_button`: Press the system button.\n* `open`: Open an app on the device.\n* `wait`: Wait specified seconds for the change to happen.\n* `terminate`: Terminate the current task and report its completion status.", "enum": ["key", "click", "long_press", "swipe", "type", "system_button", "open", "wait", "terminate"], "type": "string"}, "coordinate": {"description": "(x, y): The x (pixels from the left edge) and y (pixels from the top edge) coordinates to move the mouse to. Required only by `action=click`, `action=long_press`, and `action=swipe`.", "type": "array"}, "coordinate2": {"description": "(x, y): The x (pixels from the left edge) and y (pixels from the top edge) coordinates to move the mouse to. Required only by `action=swipe`.", "type": "array"}, "text": {"description": "Required only by `action=key`, `action=type`, and `action=open`.", "type": "string"}, "time": {"description": "The seconds to wait. Required only by `action=long_press` and `action=wait`.", "type": "number"}, "button": {"description": "Back means returning to the previous interface, Home means returning to the desktop, Menu means opening the application background menu, and Enter means pressing the enter. Required only by `action=system_button`", "enum": ["Back", "Home", "Menu", "Enter"], "type": "string"}, "status": {"description": "The status of the task. Required only by `action=terminate`.", "type": "string", "enum": ["success", "failure"]}}, "required": ["action"], "type": "object"}, "args_format": "Format the arguments as a JSON object."}}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <args-json-object>}
</tool_call>
"""

        screenshot = state["screenshot"]

        screenshot = self.resize(screenshot)

        # ------------------------------SOM----------------------------#
        # xml = state["xml"]
        # xml_cleaner = XMLCleaner(xml)
        # elements = xml_cleaner.get_final_elements()
        # self.current_elements = elements

        # # Decode base64 to numpy array
        # img_bytes = base64.b64decode(screenshot)
        # img_array = np.frombuffer(img_bytes, dtype=np.uint8)
        # imgcv = cv2.imdecode(img_array, cv2.IMREAD_COLOR)
        # for i, element in enumerate(elements):
        #     try:
        #         x1, y1, x2, y2 = element["bounds"]
        #         label = i + 1
        #         color = (250, 0, 0)
        #         imgcv = ps.putBText(
        #             imgcv,
        #             label,
        #             text_offset_x=(x1 + x2) // 2 + 10,
        #             text_offset_y=(y1 + y2) // 2 + 10,
        #             vspace=10,
        #             hspace=10,
        #             font_scale=1,
        #             thickness=2,
        #             background_RGB=color,
        #             text_RGB=(255, 250, 250),
        #             alpha=0.5,
        #         )
        #     except Exception as e:
        #         pass
        # _, buffer = cv2.imencode(".png", imgcv)
        # screenshot = base64.b64encode(buffer).decode("utf-8")
        # ------------------------------SOM----------------------------#

        history_actions = []
        for m in history["agent_messages"]:
            pattern = r"<tool_call>\s*(.*)\s*</tool_call>"
            match = re.search(pattern, m)
            if match:
                m_str = match.group(1).strip()
            else:
                m_str = json.dumps({"action": "end", "answer": ""})
            try:
                dic = json.loads(m_str)
                action = dic["arguments"]
                history_actions.append(action)
            except Exception as e:
                history_actions.append(m_str)

        action_history_str = []
        for i, action in enumerate(history_actions):
            action_history_str.append(f"Step{i+1}: {action}")
        action_history_str = ", ".join(action_history_str)

        user_prompt = f"The user query:  {task}\nTask progress (You have done the following operation on the current device): {action_history_str}; <image>"

        response = self.client.chat.completions.create(
            # model="qwen2.5-vl",
            model="Qwen2.5-VL-7B-Instruct",
            
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": user_prompt},
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image;base64,{screenshot}"},
                        },
                    ],
                },
            ],
        )
        response_str = response.choices[0].message.content
        return response_str


def register(kargs: dict) -> Qwen25VLTranslator:
    return Qwen25VLTranslator(**kargs)
