import base64
import io
import re

from openai import OpenAI
from PIL import Image

from aitk.translators.base import BaseTranslator
from aitk.utils.image_utils import smart_resize


class UITarsTranslator(BaseTranslator):
    def __init__(self, max_pixels: int = 784000) -> None:
        self.client = OpenAI(
            api_key="empty",
            base_url="http://v-dev-yuxiang001-11179700-vllm1-wl0101-vtraining.vmic.xyz/v1/",
        )
        self.max_pixels = max_pixels

    def resize(self, screenshot: str) -> str:
        image = base64.b64decode(screenshot)
        image_stream = io.BytesIO(image)
        image = Image.open(image_stream)
        width, height = image.size
        new_height, new_width, h_beta, w_beta = smart_resize(
            height, width, max_pixels=self.max_pixels
        )
        self.h_beta = h_beta
        self.w_beta = w_beta
        image_resized = image.resize((new_width, new_height))
        buffer = io.BytesIO()
        image_resized.save(buffer, format="PNG")
        image_bytes = buffer.getvalue()
        base64_str = base64.b64encode(image_bytes).decode("utf-8")
        return base64_str

    def to_device(self, action: str, width: int, height: int) -> dict:
        """transform the string generated by agent to the action that can be executed on the device

        Args:
            action (Any): any action generated by agent

        Returns:
            dict: a dictionary containing the action that can be executed on the device. The format is like:
                    {"action": "open", "app": "youtube"}
                    {"action": "tap", "x": 100, "y": 100}
                    {"action": "long_press", "x": 100, "y": 100, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "swipe", "x1": 100, "y1": 100, "x2": 200, "y2": 200, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "type", "text": "hello"}
                    {"action": "enter"}
                    {"action": "back"}
                    {"action": "home"}
                    {"action": "wait", "time": 1 (optional, default to 3 second)}
                    {"action": "end", "answer": "answer to the user query (default to empty string)"}
        """
        action_str = re.search(r"Action:\s*([^\n]*)", action)
        if not action_str:
            return {"action": "end", "answer": ""}

        action_str = action_str.group(1).strip()
        h_beta = self.h_beta
        w_beta = self.w_beta

        if action_str.startswith("click"):
            print("action_str", action_str)

            coord_pattern = (
                # r"click\(start_box='\<\|box_start\|\>\((\d+),(\d+)\)\<\|box_end\|\>'\)"
                r"click\(start_box='\((\d+),(\d+)\)'\)"
            )
            match = re.search(coord_pattern, action_str)

            if match:
                x1, y1 = int(match.group(1)), int(match.group(2))
                x1, y1 = int(x1 / w_beta), int(y1 / h_beta)
            else:
                x1, y1 = 0, 0
            return {"action": "tap", "x": x1, "y": y1}
        elif action_str.startswith("open_app"):
            print("action_str", action_str)
            open_app_pattern = r"open_app\(app_name='([^']*)'\)"
            match = re.search(open_app_pattern, action_str)
            if match:
                app_name = match.group(1)
                return {"action": "open", "app": app_name}
        elif action_str.startswith("long_press"):
            print("action_str", action_str)

            coord_time_pattern = (
                r"long_press\(start_box='\((\d+),(\d+)\)', time='(\d*)'\)"
            )
            match = re.search(coord_time_pattern, action_str)

            if match:
                x1, y1, press_time = (
                    int(match.group(1)),
                    int(match.group(2)),
                    match.group(3),
                )
                x1, y1 = int(x1 / w_beta), int(y1 / h_beta)

                time = (
                    int(press_time) if press_time else 1000
                )  # Default to 1000ms if empty
            else:
                x1, y1, time = 0, 0, 1000
            return {"action": "long_press", "x": x1, "y": y1, "duration": time}
        elif action_str.startswith("scroll"):
            print("action_str", action_str)
            scroll_pattern = (
                r"scroll\(start_box='\((\d+),(\d+)\)', end_box='\((\d+),(\d+)\)'\)"
            )
            match = re.search(scroll_pattern, action_str)
            time = 1000
            if match:
                x1, y1 = int(match.group(1)), int(match.group(2))  # Start coordinates
                x3, y3 = int(match.group(3)), int(match.group(4))  # End coordinates
                x1, y1 = int(x1 / w_beta), int(y1 / h_beta)
                x3, y3 = int(x3 / w_beta), int(y3 / h_beta)
            else:
                x1, y1, x3, y3 = 0, 0, 0, 0
            return {
                "action": "swipe",
                "x1": x1,
                "y1": y1,
                "x2": x3,
                "y2": y3,
                "duration": time,
            }
        elif action_str.startswith("type"):
            print("action_str", action_str)

            content_pattern = r"type\(content='([^']*)'\)"
            match = re.search(content_pattern, action_str)

            if match:
                text = match.group(1)  # Get the content inside quotes
            else:
                text = ""
            return {"action": "type", "text": text}
        elif action_str.startswith("press_back"):
            return {"action": "back"}
        elif action_str.startswith("press_home"):
            return {"action": "home"}
        elif action_str.startswith("press_enter"):
            return {"action": "enter"}
        elif action_str.startswith("wait"):
            print("action_str", action_str)
            wait_pattern = r"wait\(time='([^']*)'\)"
            match = re.search(wait_pattern, action_str)
            if match:
                duration = int(match.group(1))
                return {"action": "wait", "time": duration}
            return {"action": "wait", "time": 3}
        elif action_str.startswith("finished"):
            finished_pattern = r"finished\(content='([^']*)'\)"
            match = re.search(finished_pattern, action_str)

            if match:
                content = match.group(1)
            else:
                content = ""
            return {"action": "end", "answer": content}
        else:
            return {"action": "end", "answer": "unknown action"}

    def to_agent(self, task: str, state: dict, history: dict) -> str:

        screenshot = state["screenshot"]
        if len(history["screenshots"]) == 1:
            history_screenshot = []
            history_conversation = []
        else:
            history_screenshot = [history["screenshots"][-2]]
            history_conversation = [history["agent_messages"][-1]]

        screenshot = self.resize(screenshot)
        history_screenshots = [self.resize(h) for h in history_screenshot]

        user_prompt = r"""You are a GUI agent. You are given a task and your action history, with screenshots. You need to perform the next action to complete the task. 

        ## Output Format
        ```\nThought: ...
        Action: ...\n```

        ## Action Space
        click(start_box='<|box_start|>(x1,y1)<|box_end|>')
        long_press(start_box='<|box_start|>(x1,y1)<|box_end|>', time='')
        type(content='') # If you want to submit your input, use \"\
        scroll(start_box='<|box_start|>(x1,y1)<|box_end|>', end_box='<|box_start|>(x3,y3)<|box_end|>')
        open_app(app_name=\'\')
        press_home()
        press_back()
        press_enter()
        finished(content='') # Submit the task regardless of whether it succeeds or fails.
        wait(time='3')  
        ## Note
        - Use English in `Thought` part.

        - Write a small plan and finally summarize your next action (with its target element) in one sentence in `Thought` part.

        ## User Instruction
        """

        messages = []
        for i, (screenshot, message) in enumerate(
            zip(history_screenshots, history_conversation)
        ):
            messages.append(
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": user_prompt + task,
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{screenshot}",
                            },
                        },
                    ],
                }
            )
            messages.append(
                {
                    "role": "assistant",
                    "content": [
                        {
                            "type": "text",
                            "text": message,
                        },
                    ],
                }
            )

        messages.append(
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": user_prompt + task,
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{screenshot}",
                        },
                    },
                ],
            },
        )

        response = self.client.chat.completions.create(
            messages=messages, model="ui_tars"
        )

        out_message = response.choices[0].message.content
        return out_message


def register(kargs: dict) -> UITarsTranslator:
    return UITarsTranslator(**kargs)
