import base64
import io
import json
import math
import re
from typing import Any, Dict, Tuple

import numpy as np
from openai import OpenAI
from PIL import Image

from aitk.translators.base import BaseTranslator
from aitk.utils.image_utils import smart_resize


class UIVenusTranslator(BaseTranslator):
    def __init__(self, max_pixels: int = 784000) -> None:
        self.client = OpenAI(
            base_url="http://v-dev-research-11179700-vllm1-wl0101-vtraining.vmic.xyz/v1/",
            api_key="empty",
        )
        self.max_pixels = max_pixels

    def to_device(self, action: str, width: int, height: int) -> dict:
        """transform the string generated by agent to the action that can be executed on the device

        Args:
            action (Any): any action generated by agent

        Returns:
            dict: a dictionary containing the action that can be executed on the device. The format is like:
                    {"action": "open", "app": "youtube"}
                    {"action": "tap", "x": 100, "y": 100}
                    {"action": "long_press", "x": 100, "y": 100, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "swipe", "x1": 100, "y1": 100, "x2": 200, "y2": 200, "duration": 1000 (optional, default to 1000ms)}
                    {"action": "type", "text": "hello"}
                    {"action": "enter"}
                    {"action": "back"}
                    {"action": "home"}
                    {"action": "wait", "time": 1 (optional, default to 3 second)}
                    {"action": "end", "answer": "answer to the user query (default to empty string)"}
        """
        action_str = self.extract_tag(action, "action")
        if not action_str:
            return {"action": "end", "answer": "No format output"}

        h_beta = self.h_beta
        w_beta = self.w_beta
        action_type, action_params = self.parse_action(action_str)

        if action_type == "Click":
            coordinate_str = action_params.get("box", "")
            if coordinate_str == "":
                return {"action": "end", "answer": "Click not parsed"}
            x, y = coordinate_str[1:-1].split(",")
            if x is None or y is None:
                return {"action": "end", "answer": "Click not parsed"}
            x, y = int(int(x) / w_beta), int(int(y) / h_beta)
            return {"action": "tap", "x": x, "y": y}
        elif action_type == "LongPress":
            coordinate_str = action_params.get("box", "")
            if coordinate_str == "":
                return {"action": "end", "answer": "Long Press not parsed"}
            x, y = coordinate_str[1:-1].split(",")
            if x is None or y is None:
                return {"action": "end", "answer": "Long Press not parsed"}
            x, y = int(int(x) / w_beta), int(int(y) / h_beta)
            if action_params.get("time") is not None:
                time = int(action_params.get("time"))
            elif action_params.get("duration") is not None:
                time = int(action_params.get("duration"))
            else:
                time = 1000
            return {"action": "long_press", "x": x, "y": y, "duration": time}
        elif action_type == "Drag":
            start_str = action_params.get("start", "")
            end_str = action_params.get("end", "")
            if start_str == "" or end_str == "":
                return {"action": "end", "answer": "Drag not parsed"}
            x1, y1 = start_str[1:-1].split(",")
            x2, y2 = end_str[1:-1].split(",")
            if x1 is None or y1 is None or x2 is None or y2 is None:
                return {"action": "end", "answer": "Drag not parsed"}
            x1, y1 = int(int(x1) / w_beta), int(int(y1) / h_beta)
            x2, y2 = int(int(x2) / w_beta), int(int(y2) / h_beta)
            if action_params.get("time") is not None:
                time = int(action_params.get("time"))
            elif action_params.get("duration") is not None:
                time = int(action_params.get("duration"))
            else:
                time = 1000
            return {
                "action": "swipe",
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "duration": time,
            }
        elif action_type == "Scroll":
            start_str = action_params.get("start", "")
            end_str = action_params.get("end", "")
            if start_str == "" or end_str == "":
                if "direction" in action_params:
                    direction = action_params.get("direction")
                    if direction == "up":
                        x1, y1 = width // 2, height * 3 // 4
                        x2, y2 = width // 2, height // 4
                    elif direction == "down":
                        x1, y1 = width // 2, height // 4
                        x2, y2 = width // 2, height * 3 // 4
                    elif direction == "left":
                        x1, y1 = width * 4 // 5, height // 2
                        x2, y2 = width // 5, height // 2
                    elif direction == "right":
                        x1, y1 = width // 5, height // 2
                        x2, y2 = width * 4 // 5, height // 2
                else:
                    return {"action": "end", "answer": "Scroll not parsed"}
            else:
                x1, y1 = start_str[1:-1].split(",")
                x2, y2 = end_str[1:-1].split(",")
                if x1 is None or y1 is None or x2 is None or y2 is None:
                    return {"action": "end", "answer": "Scroll not parsed"}
                x1, y1 = int(int(x1) / w_beta), int(int(y1) / h_beta)
                x2, y2 = int(int(x2) / w_beta), int(int(y2) / h_beta)
            if action_params.get("time") is not None:
                time = int(action_params.get("time"))
            elif action_params.get("duration") is not None:
                time = int(action_params.get("duration"))
            else:
                time = 1000
            return {
                "action": "swipe",
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "duration": time,
            }
        elif action_type == "Type":
            if "content" in action_params:
                return {"action": "type", "text": action_params.get("content", "")}
            return {"action": "end", "answer": "Type text not parsed"}
        elif action_type == "PressBack":
            return {"action": "back"}
        elif action_type == "PressHome":
            return {"action": "home"}
        elif action_type == "PressEnter":
            return {"action": "enter"}
        elif action_type == "Launch":
            if "app" in action_params:
                app_name = action_params.get("app", "")
                return {"action": "open", "app": app_name.lower()}
            return {"action": "end", "answer": "Open app not parsed"}
        elif action_type == "Wait":
            if action_params.get("time") is not None:
                time = action_params.get("time")
            elif action_params.get("duration") is not None:
                time = action_params.get("duration")
            else:
                time = 3
            return {"action": "wait", "time": time}
        elif action_type == "Finished":
            content = action_params.get("content", "")
            return {"action": "end", "answer": content}
        else:
            return {"action": "end", "answer": "unknown action"}

    def resize(self, screenshot: str) -> str:
        image = base64.b64decode(screenshot)
        image_stream = io.BytesIO(image)
        image = Image.open(image_stream)
        width, height = image.size
        new_height, new_width, h_beta, w_beta = smart_resize(
            height, width, max_pixels=self.max_pixels
        )
        self.h_beta = h_beta
        self.w_beta = w_beta
        image_resized = image.resize((new_width, new_height))
        buffer = io.BytesIO()
        image_resized.save(buffer, format="PNG")
        image_bytes = buffer.getvalue()
        base64_str = base64.b64encode(image_bytes).decode("utf-8")
        return base64_str

    def parse_action(self, action_str: str) -> Tuple[str, Dict[str, Any]]:
        """Parse action string into action type + params."""
        pattern = r"^(\w+)\((.*)\)$"
        match = re.match(pattern, action_str.strip(), re.DOTALL)
        if not match:
            print(f"Invalid action type: {action_str}")
            return "", {}

        action_type, params_str = match.group(1), match.group(2).strip()
        params = {}

        if params_str:
            try:
                # split by comma not inside parentheses
                param_pairs = re.split(r",(?![^(]*\))", params_str)
                for pair in param_pairs:
                    if "=" in pair:
                        key, value = pair.split("=", 1)
                        params[key.strip()] = value.strip().strip("'").strip()
                    else:
                        params[pair.strip()] = None
            except Exception as e:
                print(f"Parse param failed: {e}")
                return action_type, {}
        return action_type, params

    def extract_tag(self, content: str, tag: str) -> str:
        """Extract latest <tag>...</tag> content from model output."""
        pattern = rf"<{tag}>(.*?)</{tag}>"
        matches = list(re.finditer(pattern, content, re.DOTALL))
        if not matches:
            print(f"{tag} Not Found")
            return ""
        return matches[-1].group(1).strip()

    def to_agent(self, task: str, state: dict, history: dict) -> str:
        """Given the task, current state and the agent history, interact with the agent and get the output

        Args:
            task (str): the task to be executed
            state (dict): the current state of the device
                - xml: the XML of the current state of the device in string format
                - screenshot: the screenshot of the current state of the device in base64 format
                - package: the package of the current app
                - activity: the activity of the current app
            history (dict): the history of the device in the current task
                - xmls: a list of XMLs of the device in the previous steps
                - screenshots: a list of screenshots of the device in the previous steps
                - actions: a list of actions of the device in the previous steps
                - agent_messages: a list of messages from the agent in the previous steps
                - packages: a list of packages of the apps in the previous steps
                - activities: a list of activities of the apps in the previous steps
        Returns:
            str: the output generated by the agent
        """
        user_prompt = """**You are a GUI Agent.**
Your task is to analyze a given user task, review current screenshot and previous actions, and determine the next action to complete the task.

### User Task
{user_task}

### Previous Actions
{previous_actions}

### Available Actions
Click(box=(x1, y1))
Drag(start=(x1, y1), end=(x2, y2))
Scroll(start=(x1, y1), end=(x2, y2), direction='down/up/right/left')
Type(content='')
Launch(app='')
Wait()
Finished(content='')
CallUser(content='')
LongPress(box=(x1, y1))
PressBack()
PressHome()
PressEnter()
PressRecent()

### Instruction
- Make sure you understand the task goal to avoid wrong actions.
- Examine the screenshot carefully. History may be unreliable.
- For user questions, reply with `CallUser`, then `Finished` if done.
- Explore screen content using scroll in different directions.
- Copy text: select → click `copy`.
- Paste text: long press text box → click `paste`.
- First reason inside <think>, then provide <action>, then summarize in <conclusion>.
"""

        screenshot = state["screenshot"]

        screenshot = self.resize(screenshot)

        history_actions = []
        for m in history["agent_messages"]:
            action_str = self.extract_tag(m, "action")
            history_actions.append(action_str)

        action_history_str = []
        for i, action in enumerate(history_actions):
            action_history_str.append(f"Step{i+1}: {action}")
        action_history_str = ", ".join(action_history_str)

        response = self.client.chat.completions.create(
            model="ui_venus",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": user_prompt.format(
                                user_task=task, previous_actions=action_history_str
                            ),
                        },
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image;base64,{screenshot}"},
                        },
                    ],
                },
            ],
        )
        response_str = response.choices[0].message.content
        return response_str


def register(kargs: dict) -> UIVenusTranslator:
    return UIVenusTranslator(**kargs)
