app_package = {
    "bluecoins": "com.rammigsoftware.bluecoins",
    "booking": "com.booking",
    "booking.com": "com.booking",
    "google calendar": "com.google.android.calendar",
    "calendar": "com.google.android.calendar",
    "cnn": "com.cnn.mobile.android.phone",
    "coursera": "org.coursera.android",
    "doordash": "com.dd.doordash",
    "fitbit": "com.fitbit.FitbitMobile",
    "gmail": "com.google.android.gm",
    "google maps": "com.google.android.apps.maps",
    "maps": "com.google.android.apps.maps",
    "google play": "com.android.vending",
    "google play store": "com.android.vending",
    "googleplaybooks": "com.google.android.apps.books",
    "google play books": "com.google.android.apps.books",
    "googletasks": "com.google.android.apps.tasks",
    "google tasks": "com.google.android.apps.tasks",
    "tasks": "com.google.android.apps.tasks",
    "instagram": "com.instagram.android",
    "quora": "com.quora.android",
    "smart news": "jp.gocro.smartnews.android",
    "target": "com.target.ui",
    "wish": "com.contextlogic.wish",
    "yelp": "com.yelp.android",
    "youtube": "com.google.android.youtube/.app.honeycomb.Shell$HomeActivity",
    "ytmusic": "com.google.android.apps.youtube.music",
    "youtube music": "com.google.android.apps.youtube.music",
}
