device:
  udid: emulator-5554 # 127.0.0.1:6555 is the default udid for Genymotion. emulator-5554 is the default udid for Android Virtual Device
  avd_name: A3V2 # the name of the base AVD

translator: qwen25_vl # the translator to use for the task execution (the file name of the translator file in the aitk/translators directory)
translator_args:
  # max_pixels: 784000
  max_pixels: 2665000

experiment:
  name: qwen25vl_test
  save_root_dir: agent_trajectories/
  tasks: tasks/tasks.jsonl # use the task jsonl file
  backend: adb # select from adb or appium
  screen_record: false # whether to record the process of the task execution, only support Appium as backend. ADB doesn't support this feature
  record_resolution: [1080, 1920] # the resolution of the screen recording in pixels if screen_record is on
  resume_exp: null # the path of the experiment folder to resume from
