data_dir: "agent_trajectories/qwen25vl_benchmark" # path to the data directory. Can be task folder or a parent folder containing several tasks

eval:
  base_url: "" # base url of the model deployed by vllm
  api_key: "" # api key of the model deployed by vllm
  model: "" # model name
  batch_size: 8
